# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - all_controller

  all_controller:
    type: FollowJointTrajectory
    joints:
      - joint1
      - joint2