services:
  ros_noetic:
    build:
      context: ./noetic_ws
    volumes:
      - ./noetic_ws:/root/catkin_ws
    network_mode: "host"    # Use host network mode to avoid issues with ROS networking TODO: Check if this is needed
    privileged: true        # Needed if you want access to hardware, e.g., USB devices TODO: Check if this is needed
    stdin_open: true
    tty: true
