services:
  ros2:
    build:
      context: .
    container_name: ros2_humble
    devices:
      - /dev/video0:/dev/video0           # Required for camera access
      - /dev/video1:/dev/video1           # Required for camera access
    privileged: true                      # Required for camera access
    environment:
      - DISPLAY=${DISPLAY}                # Required for GUI applications
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix     # Required for GUI applications
      - ./:/root/marvin/
    tty: true
    stdin_open: true
    command: /bin/bash