planning_pipelines:
  - ompl

ompl:
  # Default planner configuration
  planner_configs:
    - RRTConnect

  # Plugin details
  type: ompl_interface/OMPLPlanner
  request_adapters:
    - default_planner_request_adapters/AddTimeParameterization
    - default_planner_request_adapters/FixWorkspaceBounds
    - default_planner_request_adapters/FixStartStateBounds
    - default_planner_request_adapters/FixStartStateCollision
    - default_planner_request_adapters/FixStartStatePathConstraints

RRTConnect:
  type: geometric::RRTConnect
  range: 0.0  # Default range; you can adjust this based on your robot's workspace
  goal_bias: 0.05

# Optional: Configure other planners if needed
PRM:
  type: geometric::PRM
  max_nearest_neighbors: 10

workspace_parameters:
  min_x: -2.0
  min_y: -2.0
  min_z: -2.0
  max_x: 2.0
  max_y: 2.0
  max_z: 2.0
